### ISSUE TITLE
Inaccurate  Cursor Tracking Issue

### ISSUE THREAD

**Issue by LydiaZhou** [Cheng-Jiang/SDD-Project#4]
The place cursor click on is not where the "pencil" draws. It could due to either the problem of the JS cursor position function, or the specialty of the canvas.

**Comment by Cheng-Jiang** [comment]
OS: macOS Catalina Version 10.15 (19A583)
Browser: Safari Version 13.0.2 (15608.2.30.1.1)

**Comment by Cheng-Jiang** [comment]
Fixed
